name: loyaute
description: A membership app.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # additional dependencies
  cupertino_icons: ^1.0.2
  go_router: ^10.1.2
  fluttertoast: ^8.1.2
  provider: ^6.0.5
  barcode_widget: ^2.0.4
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
  - family: PlusJakartaSans
    fonts:
      - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-VariableFont_wght.ttf
  - family: PlusJakartaSansItalic
    fonts:
      - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Italic-VariableFont_wght.ttf
  - family: OCRAExtended
    fonts:
      - asset: assets/fonts/OCRAExtended/OCRAExtended.TTF

